-- lua/chat/skills/setup-nvim-plugin-test.lua
-- /setup-nvim-plugin-test - Generate a user message that asks the LLM to
-- scaffold a Neovim plugin test system, referencing wsdjeg/chat.nvim's
-- test infrastructure via GitHub raw URLs.
--
-- Usage:
--   /setup-nvim-plugin-test

return {
  name = 'setup-nvim-plugin-test',
  description = 'Set up Neovim plugin test system (references wsdjeg/chat.nvim)',
  handler = function(_, _)
    local lines = {
      '请为当前项目搭建 Neovim 插件测试系统及完整的 CI/CD 配置。',
      '',
      '参考 wsdjeg/chat.nvim 仓库的测试基础设施和工程配置，以下是相关文件的 GitHub raw 链接，',
      '请先 fetch 这些链接获取具体内容，然后根据当前项目的实际情况生成对应文件：',
      '',
      '## 参考文件',
      '',
      '### 第一步：项目规范（优先执行）',
      '',
      '1. **AGENTS.md** (AI 编码助手规范文件)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/AGENTS.md',
      '',
      '### 第二步：测试基础设施',
      '',
      '2. **Makefile** (测试入口、依赖安装、PATTERN 过滤)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/Makefile',
      '',
      '3. **test/minimal_init.lua** (headless 测试最小配置)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/test/minimal_init.lua',
      '',
      '4. **test/run.lua** (luaunit 测试运行器)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/test/run.lua',
      '',
      '5. **test/install_deps.lua** (跨平台依赖安装器)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/test/install_deps.lua',
      '',
      '### 第三步：GitHub Actions 工作流',
      '',
      '6. **.github/workflows/test.yml** (CI 测试工作流)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/.github/workflows/test.yml',
      '',
      '7. **.github/workflows/luarocks.yml** (LuaRocks 发布工作流)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/.github/workflows/luarocks.yml',
      '',
      '8. **.github/workflows/release-please.yml** (自动化发布工作流)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/.github/workflows/release-please.yml',
      '',
      '### 第四步：release-please 配置文件',
      '',
      '9. **.github/release-please-config.json** (release-please 配置)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/.github/release-please-config.json',
      '',
      '10. **.github/release-please-manifest.json** (release-please 版本清单)',
      '    https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/.github/release-please-manifest.json',
      '',
      '## 执行顺序（严格按此顺序）',
      '',
      '### 第一步：生成 AGENTS.md 并设置为 system prompt',
      '',
      '1. fetch AGENTS.md 参考链接获取内容',
      '2. 先读取当前项目结构（list_directory、read_file），了解项目模块名、目录结构',
      '3. 根据当前项目实际情况生成 `AGENTS.md`，包含：',
      '   - 项目结构说明（根据实际目录树）',
      '   - 编码规范（Lua 风格、命名约定）',
      '   - 测试说明（luaunit、make test、PATTERN 过滤）',
      '   - 提交规范（Conventional Commits）',
      '   - 文件操作规范（overwrite only、禁止 replace/insert/delete）',
      '   - 禁止修改的文件列表',
      '4. 使用 `@set_prompt` 工具将生成的 AGENTS.md 设置为当前会话的 system prompt',
      '5. 后续所有文件的生成都必须遵循 AGENTS.md 中的规范',
      '',
      '### 第二步：逐一生成测试基础设施文件',
      '',
      '按以下顺序逐一生成，每生成一个文件后立即验证（read_file 检查语法），',
      '确保正确后再生成下一个：',
      '',
      '1. `test/minimal_init.lua` - 根据项目模块名加载插件',
      '2. `test/run.lua` - 支持 PATTERN 过滤、自动发现 `test/**/*_spec.lua`',
      '3. `test/install_deps.lua` - 跨平台（curl / powershell / wget fallback）',
      '4. `Makefile` - 支持 `make test`、`make test PATTERN=xxx`、`make install-deps`、`make clean`',
      '5. `test/example_spec.lua` - 示例测试文件',
      '6. 更新 `.gitignore`，添加 `test/.deps/` 排除测试依赖目录（如已有 .gitignore 则追加，没有则创建）',
      '',
      '### 第三步：逐一生成 CI/CD 工作流文件',
      '',
      '1. `.github/workflows/test.yml` - push 到 main 和 master 分支以及 PR 时触发，',
      '   矩阵覆盖 Neovim nightly/stable × ubuntu/windows/macos',
      '2. `.github/workflows/luarocks.yml` - 推送 tag 时自动发布到 LuaRocks',
      '3. `.github/workflows/release-please.yml` - push 到 master 时自动创建 release PR，',
      '   必须引用以下配置文件路径（与 chat.nvim 保持一致）：',
      '   - `config-file: .github/release-please-config.json`',
      '   - `manifest-file: .github/release-please-manifest.json`',
      '   使用 `googleapis/release-please-action@v4`，token 使用 `RELEASE_PLEASE_TOKEN` secret',
      '',
      '### 第四步：逐一生成 release-please 配置文件',
      '',
      '注意：配置文件路径必须与 release-please.yml 中引用的路径一致：',
      '- `config-file: .github/release-please-config.json`',
      '- `manifest-file: .github/release-please-manifest.json`',
      '',
      '1. `.github/release-please-config.json` - 参考 chat.nvim 的配置，包含：',
      '   - `release-type: simple`',
      '   - `packages` 配置（`changelog-path`、`bump-minor-pre-major`、`bump-patch-for-minor-pre-major`）',
      '   - `changelog-sections` 定义各 commit 类型的 changelog 分组（feat/fix/refactor/perf/docs/test/security 显示，chore/style/build/ci 隐藏）',
      '   - `$schema` 指向 release-please 官方 schema',
      '2. `.github/release-please-manifest.json` - 初始版本号设为 0.1.0',
      '',
      '### 第五步：验证 release-please-manifest.json 版本号',
      '',
      '生成 `.github/release-please-manifest.json` 后，必须验证其中的版本号是否正确：',
      '1. 使用 `@git_fetch` 同步远程 tags（`tags=true`）',
      '2. 使用 `@git_tag` 列出当前仓库所有 tags（`action="list"`）',
      '3. 将 manifest.json 中的版本号与 tags 列表对比：',
      '   - 如果 tags 列表为空，说明是全新项目，版本号应为 `0.1.0`',
      '   - 如果 tags 列表非空，找到最高版本号，manifest.json 中的版本号应与之一致',
      '   - 如果不一致，修改 manifest.json 至正确版本号',
      '',
      '## 通用要求',
      '',
      '- 严格按上述顺序执行，先 AGENTS.md + set_prompt，再逐一生成其他文件',
      '- 每生成一个文件后，用 read_file 验证内容正确性',
      '- 如果已有同名文件，先用 read_file 读取并验证是否符合上述要求，',
      '  符合则跳过，不符合则修改至符合要求',
      '- 生成的所有文件都必须符合 AGENTS.md 中定义的规范',
    }

    return {
      content = table.concat(lines, '\n'),
      role = 'user',
      request = true,
    }
  end,
}

