-- lua/chat/skills/setup-nvim-plugin-test.lua
-- /setup-nvim-plugin-test - Generate a user message that asks the LLM to
-- scaffold a Neovim plugin test system, referencing wsdjeg/chat.nvim's
-- test infrastructure via GitHub raw URLs.
--
-- Usage:
--   /setup-nvim-plugin-test

return {
  name = 'setup-nvim-plugin-test',
  description = 'Set up Neovim plugin test system (references wsdjeg/chat.nvim)',
  handler = function(_, _)
    local lines = {
      '请为当前项目搭建 Neovim 插件测试系统及完整的 CI/CD 配置。',
      '',
      '参考 wsdjeg/chat.nvim 仓库的测试基础设施和工程配置，以下是相关文件的 GitHub raw 链接，',
      '请先 fetch 这些链接获取具体内容，然后根据当前项目的实际情况生成对应文件：',
      '',
      '## 参考文件',
      '',
      '### 测试基础设施',
      '',
      '1. **Makefile** (测试入口、依赖安装、PATTERN 过滤)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/Makefile',
      '',
      '2. **test/minimal_init.lua** (headless 测试最小配置)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/test/minimal_init.lua',
      '',
      '3. **test/run.lua** (luaunit 测试运行器)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/test/run.lua',
      '',
      '4. **test/install_deps.lua** (跨平台依赖安装器)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/test/install_deps.lua',
      '',
      '### GitHub Actions 工作流',
      '',
      '5. **.github/workflows/test.yml** (CI 测试工作流)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/.github/workflows/test.yml',
      '',
      '6. **.github/workflows/luarocks.yml** (LuaRocks 发布工作流)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/.github/workflows/luarocks.yml',
      '',
      '7. **.github/workflows/release-please.yml** (自动化发布工作流)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/.github/workflows/release-please.yml',
      '',
      '### JSON 配置文件',
      '',
      '8. **.github/release-please-config.json** (release-please 配置)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/.github/release-please-config.json',
      '',
      '9. **.github/release-please-manifest.json** (release-please 版本清单)',
      '   https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/.github/release-please-manifest.json',
      '',
      '### 项目规范',
      '',
      '10. **AGENTS.md** (AI 编码助手规范文件)',
      '    https://raw.githubusercontent.com/wsdjeg/chat.nvim/master/AGENTS.md',
      '',
      '## 要求',
      '',
      '### 测试系统',
      '',
      '- 使用 luaunit 作为测试框架',
      '- Makefile 支持 `make test`、`make test PATTERN=xxx`、`make install-deps`、`make clean`',
      '- test/minimal_init.lua 中需要根据当前项目的模块名加载插件',
      '- test/run.lua 需支持 PATTERN 过滤、自动发现 `test/**/*_spec.lua`',
      '- test/install_deps.lua 需跨平台（curl / powershell / wget fallback）',
      '- 生成一个 `test/example_spec.lua` 示例测试文件',
      '',
      '### CI/CD 工作流',
      '',
      '- 生成 `.github/workflows/test.yml`，在 push 到 main 和 PR 时触发，',
      '  矩阵覆盖 Neovim nightly/stable × ubuntu/windows/macos',
      '- 生成 `.github/workflows/luarocks.yml`，在推送 tag 时自动发布到 LuaRocks',
      '- 生成 `.github/workflows/release-please.yml`，在 push 到 main 时自动创建 release PR',
      '- 生成 `.github/release-please-config.json`，根据项目实际情况配置 release-please',
      '- 生成 `.github/release-please-manifest.json`，初始版本号设为 0.1.0',
      '',
      '### 项目规范',
      '',
      '- 生成 `AGENTS.md`，包含项目结构说明、编码规范、测试说明、提交规范等',
      '',
      '### 通用要求',
      '',
      '- 先读取当前项目结构，确保生成的文件与项目实际模块名和结构匹配',
      '- 如果已有同名文件则跳过，不要覆盖',
    }

    return {
      content = table.concat(lines, '\n'),
      role = 'user',
      request = true,
    }
  end,
}

