name: Run Lint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y lua-check
      
      - name: Run lint
        run: make lint

